// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "github.com/mathefer/tc-fiap-product/internal/product/domain/entities"
	commands "github.com/mathefer/tc-fiap-product/internal/product/usecase/commands"

	mock "github.com/stretchr/testify/mock"
)

// MockGetProductUseCase is an autogenerated mock type for the GetProductUseCase type
type MockGetProductUseCase struct {
	mock.Mock
}

type MockGetProductUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetProductUseCase) EXPECT() *MockGetProductUseCase_Expecter {
	return &MockGetProductUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: command
func (_m *MockGetProductUseCase) Execute(command *commands.GetProductCommand) ([]*entities.Product, error) {
	ret := _m.Called(command)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []*entities.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(*commands.GetProductCommand) ([]*entities.Product, error)); ok {
		return rf(command)
	}
	if rf, ok := ret.Get(0).(func(*commands.GetProductCommand) []*entities.Product); ok {
		r0 = rf(command)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(*commands.GetProductCommand) error); ok {
		r1 = rf(command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetProductUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGetProductUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - command *commands.GetProductCommand
func (_e *MockGetProductUseCase_Expecter) Execute(command interface{}) *MockGetProductUseCase_Execute_Call {
	return &MockGetProductUseCase_Execute_Call{Call: _e.mock.On("Execute", command)}
}

func (_c *MockGetProductUseCase_Execute_Call) Run(run func(command *commands.GetProductCommand)) *MockGetProductUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*commands.GetProductCommand))
	})
	return _c
}

func (_c *MockGetProductUseCase_Execute_Call) Return(_a0 []*entities.Product, _a1 error) *MockGetProductUseCase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetProductUseCase_Execute_Call) RunAndReturn(run func(*commands.GetProductCommand) ([]*entities.Product, error)) *MockGetProductUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetProductUseCase creates a new instance of MockGetProductUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetProductUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetProductUseCase {
	mock := &MockGetProductUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
