// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	dto "github.com/mathefer/tc-fiap-product/internal/product/infrastructure/api/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockProductController is an autogenerated mock type for the ProductController type
type MockProductController struct {
	mock.Mock
}

type MockProductController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductController) EXPECT() *MockProductController_Expecter {
	return &MockProductController_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: product
func (_m *MockProductController) Add(product *dto.AddProductRequestDto) error {
	ret := _m.Called(product)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*dto.AddProductRequestDto) error); ok {
		r0 = rf(product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductController_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockProductController_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - product *dto.AddProductRequestDto
func (_e *MockProductController_Expecter) Add(product interface{}) *MockProductController_Add_Call {
	return &MockProductController_Add_Call{Call: _e.mock.On("Add", product)}
}

func (_c *MockProductController_Add_Call) Run(run func(product *dto.AddProductRequestDto)) *MockProductController_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*dto.AddProductRequestDto))
	})
	return _c
}

func (_c *MockProductController_Add_Call) Return(_a0 error) *MockProductController_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductController_Add_Call) RunAndReturn(run func(*dto.AddProductRequestDto) error) *MockProductController_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockProductController) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductController_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProductController_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *MockProductController_Expecter) Delete(id interface{}) *MockProductController_Delete_Call {
	return &MockProductController_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockProductController_Delete_Call) Run(run func(id uint)) *MockProductController_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockProductController_Delete_Call) Return(_a0 error) *MockProductController_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductController_Delete_Call) RunAndReturn(run func(uint) error) *MockProductController_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: category
func (_m *MockProductController) Get(category uint) ([]*dto.GetProductResponseDto, error) {
	ret := _m.Called(category)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []*dto.GetProductResponseDto
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]*dto.GetProductResponseDto, error)); ok {
		return rf(category)
	}
	if rf, ok := ret.Get(0).(func(uint) []*dto.GetProductResponseDto); ok {
		r0 = rf(category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.GetProductResponseDto)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(category)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductController_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockProductController_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - category uint
func (_e *MockProductController_Expecter) Get(category interface{}) *MockProductController_Get_Call {
	return &MockProductController_Get_Call{Call: _e.mock.On("Get", category)}
}

func (_c *MockProductController_Get_Call) Run(run func(category uint)) *MockProductController_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockProductController_Get_Call) Return(_a0 []*dto.GetProductResponseDto, _a1 error) *MockProductController_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductController_Get_Call) RunAndReturn(run func(uint) ([]*dto.GetProductResponseDto, error)) *MockProductController_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: id, product
func (_m *MockProductController) Update(id uint, product *dto.UpdateProductRequestDto) error {
	ret := _m.Called(id, product)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, *dto.UpdateProductRequestDto) error); ok {
		r0 = rf(id, product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductController_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProductController_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - id uint
//   - product *dto.UpdateProductRequestDto
func (_e *MockProductController_Expecter) Update(id interface{}, product interface{}) *MockProductController_Update_Call {
	return &MockProductController_Update_Call{Call: _e.mock.On("Update", id, product)}
}

func (_c *MockProductController_Update_Call) Run(run func(id uint, product *dto.UpdateProductRequestDto)) *MockProductController_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(*dto.UpdateProductRequestDto))
	})
	return _c
}

func (_c *MockProductController_Update_Call) Return(_a0 error) *MockProductController_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductController_Update_Call) RunAndReturn(run func(uint, *dto.UpdateProductRequestDto) error) *MockProductController_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductController creates a new instance of MockProductController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductController {
	mock := &MockProductController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
