// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	commands "github.com/mathefer/tc-fiap-product/internal/product/usecase/commands"
	mock "github.com/stretchr/testify/mock"
)

// MockAddProductUseCase is an autogenerated mock type for the AddProductUseCase type
type MockAddProductUseCase struct {
	mock.Mock
}

type MockAddProductUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAddProductUseCase) EXPECT() *MockAddProductUseCase_Expecter {
	return &MockAddProductUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: command
func (_m *MockAddProductUseCase) Execute(command *commands.AddProductCommand) error {
	ret := _m.Called(command)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*commands.AddProductCommand) error); ok {
		r0 = rf(command)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAddProductUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockAddProductUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - command *commands.AddProductCommand
func (_e *MockAddProductUseCase_Expecter) Execute(command interface{}) *MockAddProductUseCase_Execute_Call {
	return &MockAddProductUseCase_Execute_Call{Call: _e.mock.On("Execute", command)}
}

func (_c *MockAddProductUseCase_Execute_Call) Run(run func(command *commands.AddProductCommand)) *MockAddProductUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*commands.AddProductCommand))
	})
	return _c
}

func (_c *MockAddProductUseCase_Execute_Call) Return(_a0 error) *MockAddProductUseCase_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAddProductUseCase_Execute_Call) RunAndReturn(run func(*commands.AddProductCommand) error) *MockAddProductUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAddProductUseCase creates a new instance of MockAddProductUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAddProductUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAddProductUseCase {
	mock := &MockAddProductUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
