// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "github.com/mathefer/tc-fiap-product/internal/product/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockProductRepository is an autogenerated mock type for the ProductRepository type
type MockProductRepository struct {
	mock.Mock
}

type MockProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductRepository) EXPECT() *MockProductRepository_Expecter {
	return &MockProductRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: product
func (_m *MockProductRepository) Add(product *entities.Product) error {
	ret := _m.Called(product)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Product) error); ok {
		r0 = rf(product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockProductRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - product *entities.Product
func (_e *MockProductRepository_Expecter) Add(product interface{}) *MockProductRepository_Add_Call {
	return &MockProductRepository_Add_Call{Call: _e.mock.On("Add", product)}
}

func (_c *MockProductRepository_Add_Call) Run(run func(product *entities.Product)) *MockProductRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.Product))
	})
	return _c
}

func (_c *MockProductRepository_Add_Call) Return(_a0 error) *MockProductRepository_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_Add_Call) RunAndReturn(run func(*entities.Product) error) *MockProductRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockProductRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProductRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *MockProductRepository_Expecter) Delete(id interface{}) *MockProductRepository_Delete_Call {
	return &MockProductRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockProductRepository_Delete_Call) Run(run func(id uint)) *MockProductRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockProductRepository_Delete_Call) Return(_a0 error) *MockProductRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_Delete_Call) RunAndReturn(run func(uint) error) *MockProductRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: category
func (_m *MockProductRepository) Get(category uint) ([]*entities.Product, error) {
	ret := _m.Called(category)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []*entities.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]*entities.Product, error)); ok {
		return rf(category)
	}
	if rf, ok := ret.Get(0).(func(uint) []*entities.Product); ok {
		r0 = rf(category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(category)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockProductRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - category uint
func (_e *MockProductRepository_Expecter) Get(category interface{}) *MockProductRepository_Get_Call {
	return &MockProductRepository_Get_Call{Call: _e.mock.On("Get", category)}
}

func (_c *MockProductRepository_Get_Call) Run(run func(category uint)) *MockProductRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockProductRepository_Get_Call) Return(_a0 []*entities.Product, _a1 error) *MockProductRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_Get_Call) RunAndReturn(run func(uint) ([]*entities.Product, error)) *MockProductRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: product
func (_m *MockProductRepository) Update(product *entities.Product) error {
	ret := _m.Called(product)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Product) error); ok {
		r0 = rf(product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProductRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - product *entities.Product
func (_e *MockProductRepository_Expecter) Update(product interface{}) *MockProductRepository_Update_Call {
	return &MockProductRepository_Update_Call{Call: _e.mock.On("Update", product)}
}

func (_c *MockProductRepository_Update_Call) Run(run func(product *entities.Product)) *MockProductRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.Product))
	})
	return _c
}

func (_c *MockProductRepository_Update_Call) Return(_a0 error) *MockProductRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_Update_Call) RunAndReturn(run func(*entities.Product) error) *MockProductRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductRepository creates a new instance of MockProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductRepository {
	mock := &MockProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
