// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	commands "github.com/mathefer/tc-fiap-product/internal/product/usecase/commands"
	mock "github.com/stretchr/testify/mock"
)

// MockUpdateProductUseCase is an autogenerated mock type for the UpdateProductUseCase type
type MockUpdateProductUseCase struct {
	mock.Mock
}

type MockUpdateProductUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateProductUseCase) EXPECT() *MockUpdateProductUseCase_Expecter {
	return &MockUpdateProductUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: command
func (_m *MockUpdateProductUseCase) Execute(command *commands.UpdateProductCommand) error {
	ret := _m.Called(command)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*commands.UpdateProductCommand) error); ok {
		r0 = rf(command)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUpdateProductUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUpdateProductUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - command *commands.UpdateProductCommand
func (_e *MockUpdateProductUseCase_Expecter) Execute(command interface{}) *MockUpdateProductUseCase_Execute_Call {
	return &MockUpdateProductUseCase_Execute_Call{Call: _e.mock.On("Execute", command)}
}

func (_c *MockUpdateProductUseCase_Execute_Call) Run(run func(command *commands.UpdateProductCommand)) *MockUpdateProductUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*commands.UpdateProductCommand))
	})
	return _c
}

func (_c *MockUpdateProductUseCase_Execute_Call) Return(_a0 error) *MockUpdateProductUseCase_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUpdateProductUseCase_Execute_Call) RunAndReturn(run func(*commands.UpdateProductCommand) error) *MockUpdateProductUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateProductUseCase creates a new instance of MockUpdateProductUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateProductUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateProductUseCase {
	mock := &MockUpdateProductUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
