// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	commands "github.com/mathefer/tc-fiap-product/internal/product/usecase/commands"

	mock "github.com/stretchr/testify/mock"
)

// MockDeleteProductUseCase is an autogenerated mock type for the DeleteProductUseCase type
type MockDeleteProductUseCase struct {
	mock.Mock
}

type MockDeleteProductUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeleteProductUseCase) EXPECT() *MockDeleteProductUseCase_Expecter {
	return &MockDeleteProductUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: command
func (_m *MockDeleteProductUseCase) Execute(command *commands.DeleteProductCommand) error {
	ret := _m.Called(command)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*commands.DeleteProductCommand) error); ok {
		r0 = rf(command)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeleteProductUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockDeleteProductUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - command *commands.DeleteProductCommand
func (_e *MockDeleteProductUseCase_Expecter) Execute(command interface{}) *MockDeleteProductUseCase_Execute_Call {
	return &MockDeleteProductUseCase_Execute_Call{Call: _e.mock.On("Execute", command)}
}

func (_c *MockDeleteProductUseCase_Execute_Call) Run(run func(command *commands.DeleteProductCommand)) *MockDeleteProductUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*commands.DeleteProductCommand))
	})
	return _c
}

func (_c *MockDeleteProductUseCase_Execute_Call) Return(_a0 error) *MockDeleteProductUseCase_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeleteProductUseCase_Execute_Call) RunAndReturn(run func(*commands.DeleteProductCommand) error) *MockDeleteProductUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeleteProductUseCase creates a new instance of MockDeleteProductUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeleteProductUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeleteProductUseCase {
	mock := &MockDeleteProductUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
