// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "github.com/mathefer/tc-fiap-product/internal/product/domain/entities"
	dto "github.com/mathefer/tc-fiap-product/internal/product/infrastructure/api/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockProductPresenter is an autogenerated mock type for the ProductPresenter type
type MockProductPresenter struct {
	mock.Mock
}

type MockProductPresenter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductPresenter) EXPECT() *MockProductPresenter_Expecter {
	return &MockProductPresenter_Expecter{mock: &_m.Mock}
}

// Present provides a mock function with given fields: products
func (_m *MockProductPresenter) Present(products []*entities.Product) []*dto.GetProductResponseDto {
	ret := _m.Called(products)

	if len(ret) == 0 {
		panic("no return value specified for Present")
	}

	var r0 []*dto.GetProductResponseDto
	if rf, ok := ret.Get(0).(func([]*entities.Product) []*dto.GetProductResponseDto); ok {
		r0 = rf(products)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.GetProductResponseDto)
		}
	}

	return r0
}

// MockProductPresenter_Present_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Present'
type MockProductPresenter_Present_Call struct {
	*mock.Call
}

// Present is a helper method to define mock.On call
//   - products []*entities.Product
func (_e *MockProductPresenter_Expecter) Present(products interface{}) *MockProductPresenter_Present_Call {
	return &MockProductPresenter_Present_Call{Call: _e.mock.On("Present", products)}
}

func (_c *MockProductPresenter_Present_Call) Run(run func(products []*entities.Product)) *MockProductPresenter_Present_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]*entities.Product))
	})
	return _c
}

func (_c *MockProductPresenter_Present_Call) Return(_a0 []*dto.GetProductResponseDto) *MockProductPresenter_Present_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductPresenter_Present_Call) RunAndReturn(run func([]*entities.Product) []*dto.GetProductResponseDto) *MockProductPresenter_Present_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductPresenter creates a new instance of MockProductPresenter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductPresenter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductPresenter {
	mock := &MockProductPresenter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
